name: niustack-rest-api

services:
  postgres:
    image: postgres
    container_name: niustack-rest-api-postgres
    environment:
      POSTGRES_DB: niustack-rest-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - niustack-rest-api_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  niustack-rest-api_postgres_data: